version: '3.1'

services:
  # Configuración del maestro MariaDB
  db-master:
    image: mariadb
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-master-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  myproject:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db-master
      #- db-slave

volumes:
  db-master-data:
  #db-slave-data:
