version: '3'

services:
  mariadb-master:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: replication_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker-master/init.sql:/docker-entrypoint-initdb.d/init.sql

  mariadb-slave:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_USER: replication_user
      MYSQL_PASSWORD: replication_password
    ports:
      - "3307:3306"
    volumes:
      - ./docker-slave/init.sql:/docker-entrypoint-initdb.d/init.sql
