version: '3.1'

services:
  # Configuraci贸n del maestro MariaDB
  db-master:
    image: mariadb
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-master-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  # Configuraci贸n del esclavo MariaDB
  
  # db-slave:
  #   image: mariadb
  #   command: --init-file /docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   depends_on:
  #     - db-master
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - db-slave-data:/var/lib/mysql
  #     - ./database:/docker-entrypoint-initdb.d

  # Configuraci贸n de la aplicaci贸n Scala
  myproject:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db-master
      #- db-slave

volumes:
  db-master-data:
  #db-slave-data:
